baseurl = "https://upperdelta.com/"
title = "Upper Delta"
theme = "upperdelta-theme"
languageCode = "en-us"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable comments by entering your Disqus shortname
disqusShortname = "upperdelta"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-129350298-1"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

#[[menu.main]]
#    name = "Blog"
#    url  = "/blog/"
#    weight = 2

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 2

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/upperdelta"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/Upper-Delta-528941770774769"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com/upperdelta"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:hello@upperdelta.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Upper Delta"
    defaultKeywords = ["machine learning", "data science", "services"]
    defaultDescription = "Data Science Services"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "hello@upperdelta.com"

    about_us = """
        <p>Upper Delta provides consulting services on data science and machine learning.</p>
        <p>Our team is seasoned, autonomous and hands-on. We have well rounded professionals with diverse skills that help you avoid the pitfalls of bringing a model into production, in the cloud or on-premises.</p>
        <p>Bring us your own challenge!</p>
    """
    copyright = "&reg; Upper Delta - 2017-2020 all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """
        <p><strong>Upper Delta</strong>
            <br>UPTEC Asprela I
            <br>Rua Alfredo Allen, 455
            <br>4200-135 Porto
            <br>
            <strong>Portugal</strong>
        </p>
    """
    phone = "+351 911 195 836"

    # Google Maps API key (if not set will default to not passing a key.)
    # enableGoogleMaps = true
    # googleMapsApiKey = "AIzaSyA0HWXq8WvFkhjS_oh_PtiB4mJEfbbnr2o"
    # latitude = "41.1774992"
    # longitude = "-8.605142"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Hi! Contact us on <a href="mailto:hello@upperdelta.com">hello@upperdelta.com</a>.</p>"""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = false

[params.carousel]
    enable = true
    # all items are defined in data/carousel/

[params.features]
    enable = true
    # all items are defined in data/features/

[params.usecases]
    enable = true
    # all items are defined in data/usecases/

[params.testimonials]
    enable = false
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."
    # all items are defined in data/testimonials/

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = ""
    subtitle = ""
    link_url = "#"
    link_text = ""

[params.clients]
    enable = true
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "We live and breathe data science. Get a sneak peak at what we do."
